apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-db
  namespace: test
  labels:
    app: app-with-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-with-db
  template: # Pod spec
    metadata:
      labels:
        app: app-with-db
    spec:
      containers:
        - name: db-postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
              name: flask-port
          env:
            - name: POSTGRES_PASSWORD
              value: mypassword
        - name: db-app
          image: app_with_db:001
          ports:
            - containerPort: 5000
              name: flask-port
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: mypassword